-- SYNTHETIC DATA project — Snowflake DDL for the IB Deal Pipeline & Banker
-- Staffing semantic model. Source objects mirror Salesforce extracts
-- (Account, Opportunity, User/banker roster, staffing assignments) loaded
-- from the CSVs in data/. All data is synthetic.

CREATE DATABASE IF NOT EXISTS IB_BANKING_SYNTHETIC;
CREATE SCHEMA IF NOT EXISTS IB_BANKING_SYNTHETIC.STAGING;
CREATE SCHEMA IF NOT EXISTS IB_BANKING_SYNTHETIC.CORE;

-- ---------------------------------------------------------------------------
-- Staging: raw Salesforce-style landing tables (1:1 with the extract CSVs)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE IB_BANKING_SYNTHETIC.STAGING.SF_ACCOUNT (
    ACCOUNT_ID      VARCHAR(16), ACCOUNT_NAME VARCHAR(200),
    INDUSTRY_GROUP  VARCHAR(60),  ACCOUNT_TYPE VARCHAR(60), HQ_STATE VARCHAR(8)
);
CREATE OR REPLACE TABLE IB_BANKING_SYNTHETIC.STAGING.SF_BANKER (
    BANKER_ID VARCHAR(16), BANKER_NAME VARCHAR(120), LEVEL VARCHAR(40),
    INDUSTRY_GROUP VARCHAR(60), CAPACITY_DEALS NUMBER(4),
    CAPACITY_HOURS_PER_WEEK NUMBER(5,1), IS_ACTIVE BOOLEAN, HIRE_DATE DATE
);
CREATE OR REPLACE TABLE IB_BANKING_SYNTHETIC.STAGING.SF_OPPORTUNITY (
    OPPORTUNITY_ID VARCHAR(16), OPPORTUNITY_NAME VARCHAR(120),
    ACCOUNT_ID VARCHAR(16), INDUSTRY_GROUP VARCHAR(60), PRODUCT VARCHAR(60),
    STAGE VARCHAR(40), STAGE_INDEX NUMBER(3), CLOSE_PROBABILITY NUMBER(5,4),
    DEAL_VALUE_USD NUMBER(18,2), FEE_PCT NUMBER(8,5), EXPECTED_FEE_USD NUMBER(18,2),
    OPEN_DATE DATE, CLOSE_DATE DATE, IS_CLOSED BOOLEAN, IS_WON BOOLEAN,
    LEAD_MD_ID VARCHAR(16)
);
CREATE OR REPLACE TABLE IB_BANKING_SYNTHETIC.STAGING.SF_STAFFING (
    STAFFING_ID VARCHAR(16), OPPORTUNITY_ID VARCHAR(16), BANKER_ID VARCHAR(16),
    ROLE_ON_DEAL VARCHAR(60), ALLOCATED_HOURS_PER_WEEK NUMBER(5,1),
    ASSIGNMENT_START DATE, ASSIGNMENT_END DATE
);

-- Staging views: light cleansing / typing layer over the landing tables,
-- mirroring how Salesforce objects are usually exposed to the warehouse.
CREATE OR REPLACE VIEW IB_BANKING_SYNTHETIC.STAGING.V_SF_OPPORTUNITY AS
SELECT * FROM IB_BANKING_SYNTHETIC.STAGING.SF_OPPORTUNITY
WHERE OPPORTUNITY_ID IS NOT NULL;

CREATE OR REPLACE VIEW IB_BANKING_SYNTHETIC.STAGING.V_SF_STAFFING AS
SELECT * FROM IB_BANKING_SYNTHETIC.STAGING.SF_STAFFING
WHERE STAFFING_ID IS NOT NULL AND BANKER_ID IS NOT NULL AND OPPORTUNITY_ID IS NOT NULL;

CREATE OR REPLACE VIEW IB_BANKING_SYNTHETIC.STAGING.V_SF_ACCOUNT AS
SELECT * FROM IB_BANKING_SYNTHETIC.STAGING.SF_ACCOUNT WHERE ACCOUNT_ID IS NOT NULL;

CREATE OR REPLACE VIEW IB_BANKING_SYNTHETIC.STAGING.V_SF_BANKER AS
SELECT * FROM IB_BANKING_SYNTHETIC.STAGING.SF_BANKER WHERE BANKER_ID IS NOT NULL;
