-- SYNTHETIC DATA project — star schema (Power BI semantic model) in Snowflake.
-- Facts: FACT_DEAL_PIPELINE (one row per deal), FACT_STAFFING (one row per
-- banker-deal assignment). Dimensions conformed across both facts.

CREATE OR REPLACE TABLE IB_BANKING_SYNTHETIC.CORE.DIM_INDUSTRY_GROUP (
    INDUSTRY_GROUP_KEY NUMBER AUTOINCREMENT, INDUSTRY_GROUP VARCHAR(60) UNIQUE
);
CREATE OR REPLACE TABLE IB_BANKING_SYNTHETIC.CORE.DIM_PRODUCT (
    PRODUCT_KEY NUMBER AUTOINCREMENT, PRODUCT VARCHAR(60) UNIQUE
);
CREATE OR REPLACE TABLE IB_BANKING_SYNTHETIC.CORE.DIM_STAGE (
    STAGE_KEY NUMBER, STAGE VARCHAR(40) UNIQUE, CLOSE_PROBABILITY NUMBER(5,4),
    IS_OPEN BOOLEAN, IS_CLOSED BOOLEAN, IS_WON BOOLEAN
);
CREATE OR REPLACE TABLE IB_BANKING_SYNTHETIC.CORE.DIM_BANKER (
    BANKER_KEY NUMBER AUTOINCREMENT, BANKER_ID VARCHAR(16) UNIQUE,
    BANKER_NAME VARCHAR(120), LEVEL VARCHAR(40), INDUSTRY_GROUP VARCHAR(60),
    CAPACITY_DEALS NUMBER(4), CAPACITY_HOURS_PER_WEEK NUMBER(5,1),
    IS_ACTIVE BOOLEAN, HIRE_DATE DATE
);
CREATE OR REPLACE TABLE IB_BANKING_SYNTHETIC.CORE.DIM_DATE (
    DATE_KEY NUMBER,  -- YYYYMMDD
    FULL_DATE DATE UNIQUE, CAL_YEAR NUMBER(4), CAL_QUARTER VARCHAR(7),
    CAL_MONTH NUMBER(2), MONTH_NAME VARCHAR(12), IS_MONTH_END BOOLEAN
);

CREATE OR REPLACE TABLE IB_BANKING_SYNTHETIC.CORE.FACT_DEAL_PIPELINE (
    OPPORTUNITY_ID VARCHAR(16) PRIMARY KEY,
    ACCOUNT_ID VARCHAR(16), INDUSTRY_GROUP_KEY NUMBER, PRODUCT_KEY NUMBER,
    STAGE_KEY NUMBER, OPEN_DATE_KEY NUMBER, CLOSE_DATE_KEY NUMBER,
    LEAD_MD_KEY NUMBER,
    DEAL_VALUE_USD NUMBER(18,2), EXPECTED_FEE_USD NUMBER(18,2),
    WEIGHTED_FEE_USD NUMBER(18,2),  -- EXPECTED_FEE_USD * CLOSE_PROBABILITY
    CLOSE_PROBABILITY NUMBER(5,4), DAYS_IN_STAGE NUMBER,
    IS_OPEN NUMBER(1), IS_WON NUMBER(1),
    FOREIGN KEY (INDUSTRY_GROUP_KEY) REFERENCES DIM_INDUSTRY_GROUP,
    FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_PRODUCT,
    FOREIGN KEY (STAGE_KEY) REFERENCES DIM_STAGE,
    FOREIGN KEY (LEAD_MD_KEY) REFERENCES DIM_BANKER
);

CREATE OR REPLACE TABLE IB_BANKING_SYNTHETIC.CORE.FACT_STAFFING (
    STAFFING_ID VARCHAR(16) PRIMARY KEY,
    OPPORTUNITY_ID VARCHAR(16), BANKER_KEY NUMBER, OPEN_DATE_KEY NUMBER,
    ROLE_ON_DEAL VARCHAR(60), ALLOCATED_HOURS_PER_WEEK NUMBER(5,1),
    IS_ACTIVE_ASSIGNMENT NUMBER(1),
    FOREIGN KEY (BANKER_KEY) REFERENCES DIM_BANKER,
    FOREIGN KEY (OPPORTUNITY_ID) REFERENCES FACT_DEAL_PIPELINE
);
