-- SYNTHETIC DATA project — conformed dimensions + fact loads from staging.

INSERT INTO IB_BANKING_SYNTHETIC.CORE.DIM_INDUSTRY_GROUP (INDUSTRY_GROUP)
SELECT DISTINCT INDUSTRY_GROUP FROM IB_BANKING_SYNTHETIC.STAGING.V_SF_OPPORTUNITY;

INSERT INTO IB_BANKING_SYNTHETIC.CORE.DIM_PRODUCT (PRODUCT)
SELECT DISTINCT PRODUCT FROM IB_BANKING_SYNTHETIC.STAGING.V_SF_OPPORTUNITY;

INSERT INTO IB_BANKING_SYNTHETIC.CORE.DIM_STAGE
    (STAGE_KEY, STAGE, CLOSE_PROBABILITY, IS_OPEN, IS_CLOSED, IS_WON)
SELECT DISTINCT STAGE_INDEX, STAGE, CLOSE_PROBABILITY,
       STAGE IN ('Prospecting','Qualification','Pitch','Mandate','Execution'),
       IS_CLOSED, IS_WON
FROM IB_BANKING_SYNTHETIC.STAGING.V_SF_OPPORTUNITY;

INSERT INTO IB_BANKING_SYNTHETIC.CORE.DIM_BANKER
    (BANKER_ID, BANKER_NAME, LEVEL, INDUSTRY_GROUP,
     CAPACITY_DEALS, CAPACITY_HOURS_PER_WEEK, IS_ACTIVE, HIRE_DATE)
SELECT BANKER_ID, BANKER_NAME, LEVEL, INDUSTRY_GROUP,
       CAPACITY_DEALS, CAPACITY_HOURS_PER_WEEK, IS_ACTIVE, HIRE_DATE
FROM IB_BANKING_SYNTHETIC.STAGING.V_SF_BANKER;

INSERT INTO IB_BANKING_SYNTHETIC.CORE.DIM_DATE
    (DATE_KEY, FULL_DATE, CAL_YEAR, CAL_QUARTER, CAL_MONTH, MONTH_NAME, IS_MONTH_END)
SELECT TO_NUMBER(TO_CHAR(d, 'YYYYMMDD')), d, YEAR(d),
       TO_CHAR(d, 'YYYY-"Q"Q'), MONTH(d), MONTHNAME(d),
       d = LAST_DAY(d)
FROM (SELECT DATEADD(day, SEQ4(), '2022-01-01') AS d
      FROM TABLE(GENERATOR(ROWCOUNT => 2200)));

INSERT INTO IB_BANKING_SYNTHETIC.CORE.FACT_DEAL_PIPELINE
SELECT o.OPPORTUNITY_ID, o.ACCOUNT_ID, g.INDUSTRY_GROUP_KEY, p.PRODUCT_KEY,
       s.STAGE_KEY, TO_NUMBER(TO_CHAR(o.OPEN_DATE, 'YYYYMMDD')),
       TO_NUMBER(TO_CHAR(o.CLOSE_DATE, 'YYYYMMDD')), md.BANKER_KEY,
       o.DEAL_VALUE_USD, o.EXPECTED_FEE_USD,
       o.EXPECTED_FEE_USD * o.CLOSE_PROBABILITY,
       o.CLOSE_PROBABILITY,
       DATEDIFF(day, o.OPEN_DATE, COALESCE(o.CLOSE_DATE, CURRENT_DATE())),
       IFF(s.IS_OPEN, 1, 0), IFF(o.IS_WON, 1, 0)
FROM IB_BANKING_SYNTHETIC.STAGING.V_SF_OPPORTUNITY o
JOIN IB_BANKING_SYNTHETIC.CORE.DIM_INDUSTRY_GROUP g
  ON g.INDUSTRY_GROUP = o.INDUSTRY_GROUP
JOIN IB_BANKING_SYNTHETIC.CORE.DIM_PRODUCT p ON p.PRODUCT = o.PRODUCT
JOIN IB_BANKING_SYNTHETIC.CORE.DIM_STAGE s ON s.STAGE = o.STAGE
LEFT JOIN IB_BANKING_SYNTHETIC.CORE.DIM_BANKER md ON md.BANKER_ID = o.LEAD_MD_ID;

INSERT INTO IB_BANKING_SYNTHETIC.CORE.FACT_STAFFING
SELECT st.STAFFING_ID, st.OPPORTUNITY_ID, b.BANKER_KEY,
       TO_NUMBER(TO_CHAR(st.ASSIGNMENT_START, 'YYYYMMDD')),
       st.ROLE_ON_DEAL, st.ALLOCATED_HOURS_PER_WEEK,
       IFF(st.ASSIGNMENT_END IS NULL, 1, 0)
FROM IB_BANKING_SYNTHETIC.STAGING.V_SF_STAFFING st
JOIN IB_BANKING_SYNTHETIC.CORE.DIM_BANKER b ON b.BANKER_ID = st.BANKER_ID;
