-- SYNTHETIC DATA project — analytical SQL examples over the star schema.

-- Pipeline value, weighted fee and win rate by industry group x product
SELECT g.INDUSTRY_GROUP, p.PRODUCT,
       COUNT(*)                                    AS DEALS,
       SUM(f.DEAL_VALUE_USD)                       AS PIPELINE_VALUE_USD,
       SUM(f.WEIGHTED_FEE_USD)                     AS WEIGHTED_FEE_USD,
       AVG(IFF(s.IS_CLOSED, f.IS_WON, NULL))       AS WIN_RATE_CLOSED
FROM IB_BANKING_SYNTHETIC.CORE.FACT_DEAL_PIPELINE f
JOIN IB_BANKING_SYNTHETIC.CORE.DIM_INDUSTRY_GROUP g USING (INDUSTRY_GROUP_KEY)
JOIN IB_BANKING_SYNTHETIC.CORE.DIM_PRODUCT p USING (PRODUCT_KEY)
JOIN IB_BANKING_SYNTHETIC.CORE.DIM_STAGE s USING (STAGE_KEY)
GROUP BY 1, 2 ORDER BY 1, 2;

-- Banker utilization vs capacity (mirrors src/staffing_utilization.py)
SELECT b.LEVEL, b.BANKER_NAME,
       COUNT(DISTINCT fs.OPPORTUNITY_ID) AS ACTIVE_DEALS,
       SUM(fs.ALLOCATED_HOURS_PER_WEEK)  AS ALLOCATED_HOURS,
       b.CAPACITY_DEALS, b.CAPACITY_HOURS_PER_WEEK,
       SUM(fs.ALLOCATED_HOURS_PER_WEEK) / NULLIF(b.CAPACITY_HOURS_PER_WEEK, 0)
           AS UTILIZATION_PCT
FROM IB_BANKING_SYNTHETIC.CORE.FACT_STAFFING fs
JOIN IB_BANKING_SYNTHETIC.CORE.DIM_BANKER b USING (BANKER_KEY)
WHERE fs.IS_ACTIVE_ASSIGNMENT = 1
GROUP BY 1, 2, 5, 6
ORDER BY UTILIZATION_PCT DESC;
